# Generated by Django 5.1.3 on 2025-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
