# Generated by Django 5.1.3 on 2025-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0003_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vacancy_number', models.PositiveIntegerField(default=1)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
