# Generated by Django 5.1.3 on 2025-09-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0004_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
