# Generated by Django 5.1.3 on 2025-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0005_remove_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
