# Generated by Django 5.1.3 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0006_alter_job_vacancy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='duty_station',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=10),
        ),
    ]
