# Generated by Django 5.1.3 on 2025-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0007_job_description_job_duty_station_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10),
        ),
    ]
