# Generated by Django 5.1.3 on 2025-09-26 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0008_alter_job_vacancy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=10),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='recommendations/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='awash.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='awash.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('employee', 'job')},
            },
        ),
    ]
