# Generated by Django 5.2.4 on 2025-09-29 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0009_alter_job_vacancy_type_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('new_grade', models.CharField(max_length=50)),
                ('promoted_at', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='awash.employee')),
            ],
        ),
    ]
