# Generated by Django 5.2.4 on 2025-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0010_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
