# Generated by Django 5.2.4 on 2025-09-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0011_employee_last_promotion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='position',
        ),
    ]
