# Generated by Django 5.2.4 on 2025-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awash', '0012_rename_department_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allemployee_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
    ]
