POSITION_LIST = [
"Acquired Property Administration Officer",
"Acting Branch Auditor",
"Acting Branch Auditor I (V)",
"Acting Branch Auditor I (VI)",
"Acting Branch Auditor II (VII)",
"Acting Branch Manager Class I (XIV)",
"Acting Branch Manager Class II (IX)",
"Acting Branch Manager Class II (XII)",
"Acting Branch Manager Class II (XIII)",
"Acting Branch Manager Class II Branch (X)",
"Acting Branch Manager Class III (IX)",
"Acting Branch Manager Class III (X)",
"Acting Branch Manager Class III (XII)",
"Acting Branch Manager Class IV (IX)",
"Acting Branch Manager Class IV (VIII)",
"Acting Branch Manager Class IV (X)",
"Acting Branch Manager Class IV Tier A Branch (.X)",
"Acting Branch Manager Class IV Tier A Branch (IX)",
"Acting Branch Manager Class IV Tier B Branch (IX)",
"Acting Branch Manager Class IV Tier B Branch (X)",
"Acting Branch Manager Class IV Tier C Branch (IX)",
"Acting Branch Manager Class IV Tier C Branch (X)",
"Acting Branch Manager Class IV Tier C Branch(VIII)",
"Acting Branch Operation Manager (VIII)",
"Acting Branch Operation Officer - Accounts (V)",
"Acting Branch Operation Officer - Accounts (VI)",
"Acting Branch Operation Officer - Accounts (VII)",
"Acting Branch Operation Officer - Cash (V)",
"Acting Branch Operation Officer - Cash (VI)",
"Acting Branch Operation Officer - Cash (VII)",
"Acting Branch Operation Officer Accounts",
"Acting Branch Operation Officer-Accounts (VI)",
"Acting Branch Operation Officer-Accounts (VII)",
"Acting Business Develompment Manager I (IX)",
"Acting Business Development Manager I (VI)",
"Acting Business Development Manager I (VII)",
"Acting Business Development Manager I (VIII)",
"Acting Credit Administration Officer I (VI)",
"Acting Credit Analyst II (VIII)",
"Acting Customer Service II (V)",
"Acting Customer Service Manager I (VI)",
"Acting Customer Service Manager I (VII)",
"Acting Customer Service Manager I (VIII)",
"Acting Customer Service Officer II (V)",
"Acting Digital Channel Service Officer II (V)",
"Acting Driver I (II)",
"Acting Human Resources Filling Clerk (II)",
"Acting Manager-Office Engineering Division (VIII)",
"Acting Operations Manager (VIII)",
"Acting Quality Assurance Officer I (V)",
"Acting Regional Credit Analysis and Follow Up Manager(XII)",
"Acting Regional Human Resource Business Partnership Officer (VI)",
"Acting Regional Resource Mobilization and Business Development Officer I (VI)",
"Acting Relationship Officer- Branch I (V)",
"Acting Relationship Officer-Branch II (VI)",
"Acting Relief Branch Manager Class IV Tier C Branch (IX)",
"Acting Senior Human Resource and Administration Officer (VII)",
"Acting Senior Information Technology Officer (VII)",
"Acting Trade Service Officer I (V)",
"Administrative Assistant I",
"Administrative Assistant I",
"Administrative Assistant II",
"Agency Mobile &amp; Internet Banking Officer II",
"Agency Mobile and Internate Banking Officer",
"Agency Mobile and Internet Banking Officer I",
"Agency Mobile and Internet Banking Officer II",
"Agent Banking Officer I",
"Agent Banking Officer II",
"AIB/AIC Building Administraror",
"Anti - Money Laundering Officer",
"Anti Money Laundering Officer",
"Applications Development Officer I",
"Applications Development Officer II",
"Architect",
"Archive Clerk I",
"Archives Supervisor",
"Asset and Disbursement Management Officer",
"Asset Management &amp; Disbursement Officer",
"Assistant Budget Control Accountant",
"Assistant Building &amp; Acquired Properties Administration Officer",
"Assistant Cheque Clearance Accountant",
"Assistant CSO",
"Assistant Customer Advisory Officer",
"Assistant Customer Service Officer",
"Assistant Employee Service and Succession Planning Officer",
"Assistant Employee Services &amp; Talent Management",
"Assistant Financing &amp; Investment Officer I",
"Assistant Fund Management Accountant",
"Assistant Human Resource &amp; Administration Officer",
"Assistant Payment and Settlement Accountant",
"Assistant Payroll and Staff Benefits Accountant",
"Assistant Procurement Officer",
"Assistant Property Administration Officer",
"Assistant Reconciliation Accountant",
"Assistant Report Consolidation Accountant",
"Assistant Shareholder",
"Assistant Shareholder Service Accountant",
"Assistant Talent Acquisition and On Boarding",
"Assistant Talent Acquisition and On boarding Officer",
"Assistant Talent Management Officer",
"Assistsnt Payroll and Staff Benefits Accountant",
"Associat IT Opration Officer",
"Associate Data Base Administrator",
"Associate Data Facilities Center Technical Offocer",
"Associate Digital Channels Technical Support Officer",
"Associate Hardware and Network Officer",
"Associate IT Operation Officer",
"Associate IT Service Management- Core &amp; Interface",
"Associate IT Service Management-IT Operation",
"Associate IT Services Management Officer - Service Desk I",
"Associate Learning and Evaluation Officer",
"Associate Mobile and Internet Banking Officer",
"Associate Network Administrator",
"Associate Software Engineer",
"Associate Switch Management Officer",
"Associate System Administrator",
"Attorney I",
"Attorney II",
"Audio-Visual &amp; Documentation Officer",
"Audit Supervisor",
"Auditor I",
"Auditor II",
"Auto Mechanic",
"Board Secretary",
"Branch Auditor I",
"Branch Auditor II",
"Branch Coordination Officer",
"Branch Expansion Officer",
"Branch M&amp;E Officer",
"Branch Manager - Class I",
"Branch Manager - Class II",
"Branch Manager - Class III",
"Branch Manager Class I",
"Branch Manager Class II",
"Branch Manager Class III",
"Branch Manager Class IV",
"Branch Manager Class IV Branch",
"Branch Manager Class IV Grade XII",
"Branch Manager Class IV Tier A",
"Branch Manager Class IV Tier A Branch",
"Branch Manager Class IV Tier B Branch",
"Branch Manager Class IV Tier B Branch Grade XII",
"Branch Manager Class IV Tier C",
"Branch Manager Class IV Tier C Branch",
"Branch Manager Class IV Tier C Branch Grade X",
"Branch Manager Class IV Tier C Branch Grade XII",
"Branch Manager Grade IV",
"Branch Monitoring and Evaluation Officer",
"Branch Operation Officer - Cash",
"Branch Operation Officer - Safe Box Costudy",
"Branch Operation Officer Accounts",
"Branch Operation Officer -Cash",
"Branch operation Officer-Accounts",
"Branch operation Officer-Accounts",
"Branch Operation Officer-Accounts-IFB",
"Branding and Promotion Officer",
"Budget Control Accountant",
"Budget Controll Accountant",
"Building Administrator",
"Buildings and Acquired Propeties Administration Officer",
"Business Development Manager",
"Business Development Manager I",
"Business Development Manager II",
"Business Intelligence &amp; Innovation Officer",
"Card Issuance and Replacemen Officer I",
"Card Issuance and Replacemen Officer II",
"Card Issuance and Replacement Officer I",
"Cardholder &amp; Merchant Services Officer II",
"Cardholder and Merchant Services Officer-I",
"Cardholder and Merchant Services Officer-II",
"Cash Custudy &amp; Movement Supervisor",
"Cash Office Boy",
"Cash Office Boy/Girl",
"Cash Office Girl",
"Cash Verification and Sorting Teller",
"CCTV Camera Officer &amp; Technician",
"Channel Reconciliation and Dispute Management Officer I",
"Channel Reconciliation and Dispute Management Officer II",
"Cheque Clearance Accountant",
"Chief Security and Protocol Officer",
"Cleaner - Messenger",
"Cleaner - Messenger",
"Cleaner- Messenger",
"Cleaner Supervisor",
"Cleaner-Messenger",
"Communication and CSR Officer",
"Compliance Officer",
"Compliance Officer I",
"Contact Center Assistant-Front Office",
"Contact Center Officer-Back Office",
"Contact Centre Assistant – Back Office",
"Contact Centre Officer – Front Office",
"Core Banking Operator",
"Corporate Planning ,Monitoring and Evaluation Officer",
"Corporate Transformation and Change Management Officer",
"Credit Administration and Documentation Supervisor",
"credit Administration Officer I",
"Credit Administration Officer II",
"Credit Analysis &amp; Appraisal Supervisor, Regional Office",
"Credit Analyst I",
"Credit Analyst II",
"Credit Documentation &amp; Disbursement Officer II",
"Credit Documentation &amp; Disbursement Supervisor",
"Credit Documentation and Disbursement Division Manager",
"Credit Documentation and Disbursement Officer",
"Credit Documentation and Disbursement Supervisor",
"Credit Follow up Officer",
"Credit Information Officer I",
"Credit Monitoring and Follow up Officer",
"Customer Advisory Officer I",
"Customer Advisory Officer II",
"Customer Experience Officer",
"Customer Service &amp; Operation Manager I",
"Customer Service Manager",
"Customer Service Manager I",
"Customer Service Manager I (IFB)",
"Customer Service Manager II",
"Customer Service Manager II to lead Class IV tier C Branch",
"Customer Service Manager III",
"Customer Service Officer I",
"Customer Service Officer I",
"Customer Service Officer I (IFB)",
"Customer Service Officer II",
"Customer Service Officer III",
"Data Center Attendat",
"Data Center Officer",
"Data Center Technical Officer",
"Data Centre Supervisor",
"Data Facilities Center Technical Officer II",
"Database Administrator II",
"Database Administrator-I",
"Deputy Chief - Credit Analysis and Portfolio Management",
"Deputy Director Special Class",
"Deputy Director Treasury Management",
"Digital Channel Officer I",
"Digital channel Technical support officer I",
"Digital Channel Technical support Officer II",
"Digital Channels Technical Support Officer I",
"Direct Sales Representative",
"Direct Sales Represntative",
"Director - IT Services Delivery Directorate",
"Director Business Banking Directorate",
"Director- Construction Projects and Building Administration Directorate",
"Director Corporate Banking Directorate",
"Director Credit Analysis and Appraisal Directorate",
"Director- Customer Acquisition Directorate",
"Director- Customer Experience and Quality Assurance Directorate",
"Director Finance Management Directorate",
"Director IFB Finance &amp; Investment Directorate",
"Director Import &amp; Payment Services Directorate",
"Director- Information Security Management Directorate",
"Director IT Strategy and Innovation Directorate",
"Director Portfolio Management Directorate",
"Director- Property Estimation Directorate",
"Director SME Banking Directorate",
"Director, Business Banking",
"Director, Business Solutions",
"Director, Corporate Banking",
"Director, Credit Analysis and Appraisal",
"Director, Enterprise Risk and Compliance Management",
"Director, Finance and Treasury",
"Director, Marketing and Communications",
"Director, Personal Banking",
"Director, Portfolio Management",
"Director, Product Development Directorate",
"Director, Program Management Directorate",
"Director, Shared Services",
"Director, SME Banking",
"Director, Strategy and Corporate Transformation",
"Director, Talent Acquisition and On boarding",
"Director,Talent Acquisition and On-boarding Directorate",
"Director-Adama Regional Office",
"Director-Bank Transformation Directorate",
"Director-Branch Affairs Directorate",
"Director-Communications &amp; Branding Directorate",
"Director-Compliance and KYC Directorate",
"Director-Dessie Regional Office",
"Director-Digital Marketing and Product Development Directorate",
"Director-Digital Operation Directorate",
"Director-Documentation and Disbursement Directorate",
"Director-East Addis Ababa Regional Office",
"Director-East Regional Office",
"Director-Ethics &amp; Anti-Corruption Directorate",
"Director-Export and Remittance Directorate",
"Director-General Technical &amp; Security Services Directorate",
"Director-Governmental Enterprises and Multinational Companies Directorate",
"Director-Human Resource Operations Directorate",
"Director-IFB Operations &amp; Support Directorate",
"Director-Inspection Directorate",
"Director-Institutional Banking Directorate",
"Director-Learning &amp; Talent Development Directorate",
"Director-North Addis Ababa Regional Office",
"Director-North Regional Office",
"Director-North West Regional Office",
"Director-Operational Audit Directorate",
"Director-Planning and Business Intelligence Directorate",
"Director-Procurement &amp; Supply Management Directorate",
"Director-Research &amp; Bank Modernization Directorate",
"Director-Risk Management Directorate",
"Director-South Addis Ababa Regional Office",
"Director-South Regional Office",
"Director-South West Regional Office",
"Director-Treasury Management Directorate",
"Director-West Addis Ababa Regional Office",
"Director-West Regional Office",
"Director-Wolayita Sodo Regional Officer",
"Documentation Officer",
"Driver I",
"Driver II",
"Driver III",
"Duplicating &amp; Photocopy Machine Operator",
"ECX - Supervisor",
"ECX Supervisor",
"Editor In chief",
"Electrician",
"Elevator Technician",
"Employee Service &amp; Succession Planning Officer",
"Employee Service &amp; Talent Management Officer",
"Ethics and Anti- Corruption Officer I",
"Executive Administrative Assistant",
"Executive Assistant to the CEO",
"Export Supervisor",
"External Correspondence Officer",
"File Clerk",
"Filling Clerk",
"Finance &amp; Investment Officer I",
"Financing and Investment Officer II",
"Fixed Asset Accountant",
"Fixed Asset Management Officer",
"Fixed Assets Accountant",
"Fund Management Accountant",
"Gardner",
"General Service Clerk",
"General Service Officer",
"Generator Technician",
"Graphic Design &amp; E - Media Content Developer",
"Graphic Design and E-Media Content",
"Graphic Design and E-Media Content Developer",
"Guard Lobby Man",
"Human Resource &amp; Administration Officer",
"Human Resource and Administration Officer",
"Human Resource Business Partnership Officer",
"Human Resource File clerk",
"Human Resource Filling Clerk",
"Human Resource Quality Assurance Officer",
"IFB Financing &amp; Investment Officer",
"IFB Financing &amp; Investment Officer",
"IFB Financing &amp; Investment Officer",
"IFB Operation Officer II",
"Information and Documentation Officer",
"Information Security Officer - Infrastructure I",
"Information System  Security Director",
"Information System Audit",
"Information System Audit Supervisor",
"Information Systems Audit Supervisor",
"Information Systems Auditor",
"Inspection Follow - Up Officer",
"Inspection Follow up Officer II",
"Inspection Follow Up Supervisor",
"Inspection Follow-up Officer",
"Inspector I",
"Inspector II",
"Internal Audit Supervisor",
"Issue-Cash Office Boy",
"Issue-Cash Office Girl",
"Issue-Cashier",
"IT - Project Quality Assurance Officer II",
"IT Officer I",
"IT Operation Officer II",
"IT Operations Officer I",
"IT Operations Officer II",
"IT Project Management Officer II",
"IT Project Management Officer-Business II",
"IT Project Management Officer-Technical II",
"IT Project Manager",
"IT Security Officer II",
"IT Service Management Officer Service Desk I",
"IT Service Management Officer-Channel",
"IT Service Management Officer-Channel-II",
"IT Service Management Officer-Core &amp; Interface I",
"IT Service Management Officer-Core &amp; Interface II",
"IT Service Management Officer-Core and Interfaces I",
"IT Service Management Officer-Core and Interfaces II",
"IT Service Management Officer-Service Desk I",
"IT Service Management Officer-Service Desk II",
"IT Service Management Officer-Service Desk-II",
"IT Services Officer",
"ITService Management Officer I",
"Junior-Building &amp; Acquired Property Administration Officer",
"Learning and Development Needs Analysis and Learning Delivery Officer",
"Learning and Development Strategy and Learning Evaluation Officer",
"Legal Aid",
"Legal Aids",
"Legal Officer",
"Legal Officers Advisory and Debt Recovery",
"Legal Officers, Advisory and Debt Recovery",
"Librarian",
"Lift Attendant",
"Lift Technician",
"Mail Clerk",
"Mail Clerk I",
"Maintenance Officer",
"Manager - Contact Center Division",
"Manager - IFB Finance Analysis and Appraisal Division",
"Manager - Regional Resource Mobilization &amp; Business Development I",
"Manager - Service Quality Assurance Division",
"Manager Advisory Services Division",
"Manager Agent Banking Division",
"Manager Applications Management (Core &amp; Auxiliary) Division",
"Manager ATM, POS and DC Systems Monitoring Division",
"Manager Bank Modernization Division",
"Manager Branch Expansion Division",
"Manager Branding &amp; Promotion Division",
"Manager Building &amp; Acquired Properties Administration Division",
"Manager Card Business (POS &amp; ATMs) Division",
"Manager Card Management (Card Production &amp;Distribution) Division",
"Manager Cash Management Division",
"Manager Change Management Division",
"Manager Channel Reconciliation &amp; Dispute Management Division",
"Manager Commercial Credit Appraisal Division",
"Manager Compliance Management",
"Manager Computing &amp; Data Center Division",
"Manager Construction Projects Management Division",
"Manager Credit Analysis &amp; Follow Up",
"Manager Credit Documentation And Disbursement Division",
"Manager Credit Risk Management Division",
"Manager Database Management Division",
"Manager Debt Recovery",
"Manager Debt Recovery Division",
"Manager Digital Products Development Division",
"Manager Digital Risk &amp; Quality Assurance Division",
"Manager Employee Services &amp; Succession Planning Division",
"Manager Enterprise Architecture and Vendor Management Division",
"Manager Export Division",
"Manager External Correspondence &amp; Branch Operations Division",
"Manager Financial Audit Division",
"Manager Fintechs &amp; Corporate Billers Management Division",
"Manager General Accounts &amp; Payment Division",
"Manager General Service Division",
"Manager Human Resource Business Partnership Division",
"Manager IFB Operations Division",
"Manager- IFRS Project, Financial Planning and Reporting Division",
"Manager Import Division",
"Manager Information Security Engineering Division",
"Manager Information Security Operations Division",
"Manager Information System Audit Division",
"Manager Information system security",
"Manager Inspection Division",
"Manager Issue Accounts Division",
"Manager IT Equipment and Operations Management Division",
"Manager IT Service Division",
"Manager IT Service Monitoring &amp; Control Center Division",
"Manager- IT Strategy and Business Analysis Division",
"Manager Know Your Customer Management Division",
"Manager Legal Advisory Service",
"Manager -Litigation Division",
"Manager Litigation Division Manager",
"Manager Management Audit Division",
"Manager Market Intelligence &amp; Product Development Division",
"Manager Mobile &amp; Online Business Division",
"Manager Needs Analysis and Evaluation Division",
"Manager Network Administration Division",
"Manager NGOS Service Division",
"Manager Online Banking Systems Management ( Mobile, Internet, Agency, Wallet) Division",
"Manager Operational &amp; Asset Liability Risk Management Division",
"Manager Payment Systems Management (Switch, Ecommerce, Loyalty) Division",
"Manager Payments Division",
"Manager Performance and Result Management",
"Manager Personal &amp; Diaspora Banking Division",
"Manager Planning &amp; Monitoring Division",
"Manager Portfolio Analysis Division",
"Manager Procurement Division",
"Manager Project Management Division",
"Manager Property Administration Division",
"Manager Property Evaluation",
"Manager Public Relations &amp; Corporate Social Responsibility Division",
"Manager Reconciliation Division",
"Manager- Regional Human Resource and Administration",
"Manager Regional Operations and Support Service",
"Manager Regional Operations Support and Quality Assurance",
"Manager Regional Resource Mobilization &amp; Business Development",
"Manager Religious Inst IntAgencies &amp; Embassies Service Division Manager",
"Manager Remittance Division",
"Manager Research &amp; Strategy Division",
"Manager Retail Property Estimation Division",
"Manager Security Services Division",
"Manager Shareholder Service Division",
"Manager Special Investigation Division",
"Manager Strategy Implementation &amp; Follow-up Division",
"Manager- Supplies Management Division",
"Manager System Customization &amp; Report Design Division",
"Manager System Development &amp; Integration Division",
"Manager Talent Acquisition &amp; On Boarding Division",
"Manager Talent Management Division",
"Manager Technical Services Division",
"Manager Training &amp; Development Division",
"Manager Transformation Projects Management Division",
"Manager Wholesale Customers Documentation &amp; Disbursement  Division",
"Manager Wholesale Property Estimation Division",
"Manager, Branch Operations &amp; Coordination",
"Manager, Cash Movement and Custody",
"Manager, Contact Centre &amp; Customer Experience",
"Manager, Corporate Transformation and Change Management",
"Manager, Database and System Administration",
"Manager, Employee Services and Talent Management",
"Manager, Financial and Operations Audit",
"Manager, Financial Reporting and Payment Reconciliation",
"Manager, General Services",
"Manager, Import &amp; Export",
"Manager, Inspection",
"Manager, Interest Free Banking Division",
"Manager, IT Infrastructure",
"Manager, IT Service Management",
"Manager, Market Intelligence and Product Development",
"Manager, System Development and Customization",
"Manager, Technical Services",
"Manager-Branch Expansion Division",
"Manager-Business Intelligence and Analysis Division",
"Manager-CEO Protocol &amp; Event Management",
"Manager-Communication &amp; CSR Division",
"Manager-Corporate Planning,Monitoring &amp; Evaluation",
"Manager-Procurement Division",
"Manager-Regional Operations &amp; Support Services",
"Manager-Regional Resource Mobilization &amp; Business Development",
"Manager-Strategy, Research &amp; Development",
"Market Intelligence and Product Development Officer",
"Merchant Recruitment &amp; Follow Up Officer I",
"Merchant Recruitment &amp; Follow Up Officer II",
"Messenger",
"Mobile &amp; Internate Banking Officer I",
"Mobile &amp; Internet Banking Officer II",
"Money Transfer Follow - Up Officer",
"Money Transfer Supervisor",
"NBE - Core Banking Operator",
"Need Analysis and Evaluation Officer",
"Network Administrater I",
"Network Administrator II",
"Network and Hardware Officer-I",
"Network and Hardware Officer-II",
"Note Counting &amp; Photocopy Machine Technician",
"Office Machine Technician",
"Operations Manager",
"Payment and Setlement Accountant",
"Payment and Settlement Supervisor",
"Payment Reconciliation Accountant",
"Payroll and Staff Benefits Accountant",
"Performance  and Result Management Officer",
"Performance &amp; Result Management Officer",
"Planning ,Monitoring and Evaluation Officer -Regional",
"Plumber",
"Plumber Foreman",
"Portfolio Analyst",
"Principal - IFB Branch Coordination &amp; Shariah Advisory Commitee Secretariat",
"Principal - IT Service Management Officer-Core and Interface",
"Principal - Network Administrator",
"Principal – Talent Acquisition &amp; On Boarding Officer",
"Principal Agent Banking Officer",
"Principal Applications Development Officer",
"Principal Branch Monitoring &amp; Evaluation Officer",
"Principal Branch Operation Officer",
"Principal Branches Monitoring And Evaluation Officer",
"Principal Branding &amp; Promotion Officer",
"Principal Branding and Promotion Officer",
"Principal Card Issuance and Replacement Officer",
"Principal Cheque Clearance Accountant",
"Principal Communication and CSR Officer",
"Principal Compliance Management Officer",
"Principal Corporate Planning Monitoring and Evaluation Officer",
"Principal Corporate Transformation and Change Management Officer",
"Principal Credit Follow Up",
"Principal Database Administrator",
"Principal Hardware and Network Officer",
"Principal HR Officer",
"Principal- IFB Products Development Officer",
"Principal Information Security Officer",
"Principal IT Operation Officer",
"Principal IT Project Management Officer",
"Principal IT Security Officer",
"Principal IT Service Management Officer-Service Desk",
"Principal IT Strategy and Business Analysis",
"Principal Market Intelligence and Product Development Officer",
"Principal Merchant Recruitment and Follow Up Officer",
"Principal Need Assessment Officer",
"Principal Payment &amp; Settlement Account",
"Principal Portfolio Analyst",
"Principal- Regional Human Resource &amp; Administration Officer",
"Principal Research and Development Officer",
"Principal Server and Storage Administrator",
"Principal Service Quality Assurance",
"Principal Social Media &amp; Digital Marketing Officer",
"Principal Software Engineer",
"Principal Strategy Implementation Follow-UP Officer",
"Principal System Administrator",
"Principal Talent Management Officer",
"Principal Training and Development Officer",
"Principal training need assesment &amp; evaluation officer",
"Principal Transformation Project Management Officer",
"Principal, Corporate Planning ,Monitoring and Evaluation Officer",
"Principal,Performance  and Result Management Officer",
"Principal-Business Analyst Officer",
"Principal-Cardholder and Merchant Services Officer",
"Principal-Change Management Officer",
"Principal-Credit Monitoring and Follow up Officer",
"Principal-Digital Channel Technicals Support Officer",
"Principal-HR Business Partnership Officer",
"Principal-Network Architect and Administrator",
"Principal-Partnership Management Officer",
"Principal-Performance &amp; Result Management Officer",
"Principal-Reconciliation Officer",
"Principal-Terminal management Officer",
"Procurement Officer",
"Procurement Supervisor",
"Project Manager New Head Quarter Building",
"Promotion Clerk",
"Property Evaluation Engineer",
"Property Evaluation Engineer I",
"Property Evaluation Engineer II",
"Property Valuation Engineer I",
"Public Relation &amp; Communication Officer",
"Quality Assurance Officer I",
"Quality Assurance Officer II",
"Reconcilation and Dispute Management Officer I",
"Reconciliation &amp; Dispute Management Officer I",
"Reconciliation Accountant",
"Reconciliation and Dispute Management Officer II",
"Reconciliation and Dispute Management Officer-I",
"Reconciliation and Dispute Management Officer-II",
"Regional Credit Analysis and Follow Up Manager",
"Regional Digital Channel Service Officer II",
"Regional Human Resource Business Partnership Officer",
"Regional Planning and Monitoring Officer",
"Regional Planning and Monitoring Officer I",
"Regional Planning and Monitoring Officer II",
"Regional Quality Assurance Officer I",
"Regional Relationship Manager-Banking I",
"Regional Relationship Manager-Banking II",
"Regional Resource Mobilaization &amp; Business Development Officer II",
"Regional Resource Mobilization &amp; Business Development Officer I",
"Regional Resource Mobilization &amp; Development Officer I",
"Regional Resource Mobilization &amp; Development Officer II",
"Relationship Manager - Business Banking I",
"Relationship Manager - Business Banking II",
"Relationship Manager - Conventional Banking I",
"Relationship Manager – Corporate Banking I",
"Relationship Manager – Corporate Banking II",
"Relationship Manager – Personal Banking I",
"Relationship Manager – SME Banking I",
"Relationship Manager Business Banking I",
"Relationship Manager Business Banking II",
"Relationship Manager Business Banking III",
"Relationship Manager -Corporate Banking III",
"Relationship Manager I Convectional/IFB Banking I",
"Relationship Manager I Personal &amp; SME Banking",
"Relationship Manager II Personal &amp; SME Banking",
"Relationship Manager Institutional Banking I",
"Relationship Manager Institutional Banking II",
"Relationship Manager Personal Banking II",
"Relationship Manager SME Banking II",
"Relationship Manager-Government Enterprise Service I",
"Relationship Manager-Government Enterprise Service II",
"Relationship Manager-Personal &amp; SME Banking III",
"Relationship Officer- Branch I",
"Relationship Officer- Branch II",
"Relationship Officer-Branch I",
"Relationship Officer-Branch II",
"Releif Branch Auditor II",
"Relief  Branch Manager",
"Relief Branch Manager Class III",
"Relief Branch Manager Class IV",
"Relief Branch Operation Officer - Accounts",
"Relief Branch Operation Officer - Cash",
"Remittance Supervisor",
"Rent Follow-up Officer",
"Report Consolidation Accountant",
"Research and Development Officer",
"Risk Management Officer",
"Scooter Driver",
"Security Guard",
"Security Guard - Female",
"Security Guard (IFB)",
"Security Officer",
"Senior - Customer Advisory Officer",
"Senior - Data Center Technical Officer",
"Senior - Digital channel technical support",
"Senior - IT Strategy &amp; Business Analysis Officer",
"Senior - Mobile &amp; Internet Banking Officer",
"Senior - Planning and Monitoring Officer",
"Senior - Quality Assurance Officer",
"Senior - Server &amp; Storage Administrator",
"Senior - Switch Management Officer",
"Senior Administrative Assistant",
"Senior Advisor to the CEO",
"Senior Agency, Mobile and Internet Banking Officer",
"Senior Agent Banking Officer",
"Senior Applications Development Officer",
"Senior Architect - Interior Works",
"Senior Attorney",
"Senior Auto Mechanic",
"Senior Branch Expansion officer",
"Senior Branch Monitoring and Evaluation Officer",
"Senior Branch Operation Officer",
"Senior Branding and Promotion Officer",
"Senior Budget Control Accountant",
"Senior Budget Controll Accountant",
"Senior Building and Acquired Properties Administration Officer",
"Senior Business Analyst",
"Senior Business Intelligence and Innovation Officer",
"Senior Card Issuance and Replacement Officer",
"Senior Cardholder and Merchant Service Officer",
"Senior Cash Custody and Movement Officer",
"Senior Change Management &amp; Transformation Officer",
"Senior Change Management Officer",
"Senior Channel Reconcilation &amp; Dispute Management Officer",
"Senior Cheque Clearance Accountant",
"Senior Civil Engineer",
"Senior Communication &amp; CSR Officer",
"Senior Communication Public Relations and Social Responsiblity Officer",
"Senior Communications, Public Relations and CSR Officer",
"Senior Compliance Management Officer",
"Senior Compliance Officer",
"Senior Corporate Planning Monitoring and Evaluation Officer",
"Senior Corporate Transformation and Change Management Officer",
"Senior Credit Analyst",
"Senior Credit Documentation &amp; Disbursement Officer",
"Senior Credit Documentation and Disbursement Officer",
"Senior Credit Monitoring and Follow up Officers",
"Senior Database Administrator",
"Senior Electrician",
"Senior Employee Service &amp; Succession Planning Officer",
"Senior Employee Service and Talent Management",
"Senior Enterprise Risk Officer",
"Senior Ethics &amp; Anti-Corruption Officer",
"Senior External Correspondence Officer",
"Senior Financing &amp; Investment officer",
"Senior Fixed Asset Management Officer",
"Senior Fund Management Accountant",
"Senior General Service Officer",
"Senior Generator Technician",
"Senior Hardware and Network Officer",
"Senior Human Resource and Administration Officer",
"Senior Human Resource Business Partnership Officer",
"Senior IFB Asset Management &amp; Disbursement Officer",
"Senior IFB Financing &amp; Investment Officer",
"Senior IFB Operation &amp; Branch Support Officer",
"Senior Information Security Officer",
"Senior Information Security Officer - Infrastructure",
"Senior Information System Auditer",
"Senior Inspector",
"Senior IT Operation Officer",
"Senior IT Project Quality Assurance Officer",
"Senior IT Security Officer",
"Senior IT Service Management Officer-Channel",
"Senior IT Service Management Officer-Core &amp; Interface",
"Senior IT Service Management Officer-Core and Interfaces",
"Senior IT Service Management Officer-Service Desk",
"Senior Learning and Development Needs Analysis and Learning Delivery Officer",
"Senior- Learning and Development Officer",
"Senior Machine Maintenance Officer",
"Senior Mail Officer",
"Senior Market Intelligence and Product Development Officer",
"Senior Mechanical Engineer",
"Senior Merchant Recruitment and Follow Up Officer",
"Senior Merchant Recruitment and Follow Up Officer I",
"Senior Monitering &amp; Evaluation Officer",
"Senior Needs Analysis and Evaluation Officer",
"Senior Network Administrator",
"Senior Office Machine Technician",
"Senior Officer AB &amp; AIC Building &amp; Prorerty Administration",
"Senior Payment and Reconciliation Accountant",
"Senior Payment and Settlement Accountant",
"Senior Payroll and Staff Benefits Accountant",
"Senior Performance &amp; Result Management Officer",
"Senior Planning  Monitoring and Evaluation Officer",
"Senior Portfolio Analyst",
"Senior Procurement Officer",
"Senior Project Management Officer-Business",
"Senior Project Management Officer-Technical",
"Senior Property Evaluation Engineer",
"Senior Quality Assurance Officer",
"Senior Reconciliation &amp; Dispute Management Officer",
"Senior Reconciliation Accountant",
"Senior Reconciliation and Dispute Management Officer",
"Senior Regional Planning and Monitoring Officer",
"Senior- Regional Resource Mobilization &amp;Business Development Officer",
"Senior Remittance Officer",
"Senior Report Consolidation Accountant",
"Senior Research &amp; Development Officer",
"Senior Resource Mobilization &amp; Business Development Officer",
"Senior Risk Management Officer",
"Senior Senior Cardholder and Merchant Service Officer",
"Senior Senior Cardholder and Merchant Service Officer",
"Senior Server and Storage Administrator",
"Senior Service Quality Assurance Officer",
"Senior Shareholders Service Accountant",
"Senior Social Media &amp; Digital Marketing Officer",
"Senior Software Engineer",
"Senior Strategy Implementation Follow up Officer",
"Senior Systems Admininstrator",
"Senior Systems Administrator",
"Senior Talent Acquisition and On Boarding Officer",
"Senior Talent Acquisitions and On Boarding Officer",
"Senior Talent Management Officer",
"Senior Technology Project Officer",
"Senior Terminal Management Officer",
"Senior Trade Service Officer",
"Senior Training &amp; Development Officer",
"Senior Transformation Project Officer",
"Senior Transport Officer",
"Senior, Hardware and Network Officer",
"Senior, IT Operations Officer",
"Senior, IT Operations Officer",
"Senior,Human Resource Business Partnership Officer",
"Senior,Performance  and Result Management Officer",
"Senior-IT Officer",
"Senior-Mail Officer",
"Senior-Money Transfer Follow-Up Officer",
"Senior-Monitoring and Evaluation Officer",
"Senior-Technical IT Project Management Officer",
"Server and Storage Administrator II",
"Service Accountant",
"Shareholder Service Accountant",
"Shareholder Service Supervisor",
"Social Media &amp; Digital Marketing Officer",
"Software Engineer I",
"Software Engineer II",
"Store Keeper",
"Store Keeper I",
"Stores Keeper",
"Strategy Implementation Follow Up Officer",
"Supervisor Cash Movement and Custody",
"Supervisor Cash Verification and Sorting",
"Supervisor, Cash Movement and Custody",
"Supervisor, Cash Verification and Sorting",
"Swift and Documentation Supervisor",
"Swift Operator",
"Switch Management Officer I",
"Switch Management Officer II",
"System Administrator I",
"System Administrator II",
"Systems Administrator II",
"Talent Acquisition &amp; On boarding Officer",
"Talent Acquisition and On Boarding Officer",
"Talent Acqusition &amp; Onboarding Officer",
"Talent Management Officer",
"Team Leader - Contact Center",
"Telephone Operator",
"Telephone Technician",
"Terminal Management Officer I",
"Terminal Management Officer II",
"Trade Service Officer I",
"Trade Service Officer II",
"Trade Service Supervisor",
"Training &amp; Development Officer",
"Training clerk",
"Transformation Project Management Officer",
"Transport Clerk",
"Transport Clerk I",
"Treasury Accountant",
"Van - Teller",
"Vendor Management Officer",
"Warehousing Supervisor",

]